#!/usr/bin/env node
// Writes NOTICE from the dependency trees, or checks that it is current.
//
//   node scripts/notice.mjs [--check]
//
// The Rust tree is what `cargo metadata --locked` resolves for the WebAssembly module (wasm/, for
// wasm32-unknown-unknown, default features), over normal dependency edges (build scripts and tests
// do not count). For each third-party crate the notice gives its version, its licence as its
// authors state it, the licence the package uses it under where the authors offer a choice, its
// source, the copyright lines of its licence files, and the licence texts themselves, each distinct
// text once. Heartwood Core's own NOTICE, from the revision the build uses, is carried in full. The
// JavaScript side comes from package-lock.json: the package's runtime dependencies (none today)
// and the bundler whose helpers are in its JavaScript, with the development tools summarised.
//
// Needs Node 20 or later, cargo, sdk-rust next to this repository (as for the build) and
// `npm ci`; the crate sources are read from Cargo's cache, which `cargo metadata` fills. --check
// exits with status 1 when NOTICE differs from what it would write.

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// What this repository's NOTICE covers. The rest of the file is the same in sdk-rust and
// sdk-typescript.
const CONFIG = {
  output: join(root, "NOTICE"),
  command: "npm run notice",
  header: `IceRoot SDK for TypeScript

Licensed under the Apache License, Version 2.0 (see LICENSE).

This file is generated by scripts/notice.mjs from wasm/Cargo.lock and package-lock.json; run
\`npm run notice\` after changing a dependency instead of editing it. The WebAssembly module in
this package contains compiled code of the IceRoot SDK's Rust crates (sdk-rust, Apache-2.0), of
Heartwood Core's heartwood-crypto crate, of the Rust standard library and of the third-party crates
listed below. Its JavaScript is the package's own code, the glue that wasm-bindgen generates for
the module, and the module helpers of the bundler.`,
  // The module's tree: wasm32, default features (never the test build's).
  metadata: ["--filter-platform", "wasm32-unknown-unknown", "--manifest-path", join(root, "wasm", "Cargo.toml")],
  extraEntries: (texts) => [rustStandardLibrary(texts)],
  extraSections: (texts) => javascriptSections(texts),
};

// The Rust standard library is linked into the module; it is not a crate of the tree.
function rustStandardLibrary(texts) {
  return [
    "The Rust standard library (core, alloc and std, with the crates it is built from)",
    "  Licence: MIT OR Apache-2.0 (used under Apache-2.0)",
    "  Source: https://github.com/rust-lang/rust",
    "  Copyright (c) The Rust Project Contributors",
  ].join("\n");
}

// The JavaScript side, from package-lock.json.
function javascriptSections(texts) {
  const lock = JSON.parse(readFileSync(join(root, "package-lock.json"), "utf8"));
  const packages = Object.entries(lock.packages)
    .filter(([path]) => path.startsWith("node_modules/"))
    .map(([path, entry]) => ({ path, name: path.slice(path.lastIndexOf("node_modules/") + 13), ...entry }))
    .sort((a, b) => compareText(a.name, b.name) || compareVersions(a.version, b.version));
  const runtime = packages.filter((p) => p.dev !== true && p.devOptional !== true);
  // esbuild writes its small module helpers into the bundles it makes.
  const shipped = [...runtime, ...packages.filter((p) => p.name === "esbuild")];
  const entries = shipped.map((p) => npmEntry(p, texts));

  const tools = packages.filter((p) => !shipped.includes(p));
  // The builds of one tool for each platform count once.
  const families = new Map();
  for (const p of tools) {
    const platform = /([-/])(aix|android|darwin|freebsd|linux|netbsd|openbsd|openharmony|sunos|win32)(-.*)?$/;
    const family = p.os || p.cpu ? p.name.replace(platform, "$1*") : p.name;
    const key = `${p.license ?? "not stated"}\u0000${family} ${p.version}`;
    families.set(key, (families.get(key) ?? 0) + 1);
  }
  const byLicence = new Map();
  for (const [key, count] of families) {
    const [licence, name] = key.split("\u0000");
    const list = byLicence.get(licence) ?? [];
    list.push(name.includes("*") ? `${name} (${count} platform builds)` : name);
    byLicence.set(licence, list);
  }
  const summary = [...byLicence]
    .sort(([a], [b]) => compareText(a, b))
    .map(([licence, names]) => wrap(`${licence}: ${names.join(", ")}.`, "  "));

  return [
    rule(`JavaScript (${entries.length})`),
    (runtime.length === 0
      ? "The package has no runtime JavaScript dependencies. The bundler whose helpers are in its\nJavaScript:"
      : "The package's runtime JavaScript dependencies, and the bundler whose helpers are in its\nJavaScript:"),
    entries.join("\n\n"),
    `The development tools of package-lock.json (${tools.length} packages) build, test and type check the\n` +
      "package; none of their code is in it. By licence:",
    summary.join("\n"),
  ];
}

function npmEntry(pkg, texts) {
  const dir = join(root, pkg.path);
  if (!existsSync(join(dir, "package.json"))) {
    fail(`${pkg.name} is not installed: run npm ci first`);
  }
  const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const licence = pkg.license ?? manifest.license;
  if (licence === undefined) {
    fail(`${pkg.name} ${pkg.version} states no licence`);
  }
  const chosen = choose(licence, pkg.name);
  const lines = [`${pkg.name} ${pkg.version}`];
  lines.push(`  Licence: ${licence}${chosen.join(" AND ") !== licence ? ` (used under ${chosen.join(" AND ")})` : ""}`);
  const repository = typeof manifest.repository === "string" ? manifest.repository : manifest.repository?.url;
  lines.push(
    `  Source: https://www.npmjs.com/package/${pkg.name}/v/${pkg.version}` +
      (repository ? `, ${repository.replace(/^git\+/, "").replace(/\.git$/, "")}` : ""),
  );
  const files = licenceFiles(dir);
  const copyrights = uniqueStatements(files.flatMap((file) => copyrightLines(readFileSync(join(dir, file), "utf8"))));
  for (const line of copyrights) lines.push(`  ${line}`);
  if (!copyrights.some(namesHolder)) {
    const author = typeof manifest.author === "string" ? manifest.author : manifest.author?.name;
    lines.push(`  Authors: ${author ? stripEmail(author) : `the ${pkg.name} developers (no copyright line in the package)`}`);
  }
  addTexts(texts, chosen, dir, files, `${pkg.name} ${pkg.version}`);
  return lines.join("\n");
}

// Crates of the SDK and of Heartwood Core: their licence is in LICENSE, and Heartwood Core's notice
// is carried in full.
const FIRST_PARTY = /^(iceroot-|heartwood-)/;

// Where the authors offer a choice, the first licence of this list that they offer is the one used.
const PREFERENCE = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "Zlib",
  "Unicode-3.0",
  "MIT-0",
  "CC0-1.0",
  "Unlicense",
  "CDLA-Permissive-2.0",
  "Apache-2.0 WITH LLVM-exception",
];

// Code bundled inside a crate under its own licence, which the crate's licence field does not name.
const BUNDLED = {
  "secp256k1-sys": [
    { component: "libsecp256k1, the C library the crate builds", file: "depend/secp256k1/COPYING", licence: "MIT" },
  ],
};

function main() {
  const check = process.argv.includes("--check");
  const metadata = JSON.parse(
    execFileSync(
      "cargo",
      ["metadata", "--format-version", "1", "--locked", ...CONFIG.metadata],
      { encoding: "utf8", maxBuffer: 256 * 1024 * 1024, stdio: ["ignore", "pipe", "inherit"] },
    ),
  );
  const packages = reachable(metadata);
  const text = render(packages);
  if (check) {
    const current = existsSync(CONFIG.output) ? readFileSync(CONFIG.output, "utf8") : "";
    if (current !== text) {
      console.error(`notice: NOTICE is not current; run ${CONFIG.command} and commit the result`);
      process.exit(1);
    }
    console.log(`notice: NOTICE is current (${packages.filter((p) => !FIRST_PARTY.test(p.name)).length} crates)`);
  } else {
    writeFileSync(CONFIG.output, text);
    console.log(`notice: wrote NOTICE`);
  }
}

// The packages reachable from the workspace members over normal edges, sorted by name and version.
function reachable(metadata) {
  const byId = new Map(metadata.packages.map((p) => [p.id, p]));
  const nodes = new Map(metadata.resolve.nodes.map((n) => [n.id, n]));
  const seen = new Set();
  const stack = [...metadata.workspace_members];
  while (stack.length > 0) {
    const id = stack.pop();
    if (seen.has(id)) {
      continue;
    }
    seen.add(id);
    for (const dep of nodes.get(id)?.deps ?? []) {
      if (dep.dep_kinds.some((kind) => kind.kind === null)) {
        stack.push(dep.pkg);
      }
    }
  }
  return [...seen]
    .map((id) => byId.get(id))
    .sort((a, b) => compareText(a.name, b.name) || compareVersions(a.version, b.version));
}

function compareText(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function compareVersions(a, b) {
  const pa = a.split(/[.+-]/).map((x) => (/^\d+$/.test(x) ? Number(x) : x));
  const pb = b.split(/[.+-]/).map((x) => (/^\d+$/.test(x) ? Number(x) : x));
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    if (pa[i] === pb[i]) continue;
    if (pa[i] === undefined) return -1;
    if (pb[i] === undefined) return 1;
    return pa[i] < pb[i] ? -1 : 1;
  }
  return 0;
}

// Rendering ----------------------------------------------------------------------------------

function render(packages) {
  const heartwood = packages.find((p) => p.name === "heartwood-crypto");
  if (heartwood === undefined) {
    fail("heartwood-crypto is not in the dependency tree");
  }
  const heartwoodNotice = join(dirname(heartwood.manifest_path), "..", "..", "NOTICE");
  if (!existsSync(heartwoodNotice)) {
    fail(`Heartwood Core's NOTICE is missing next to ${heartwood.manifest_path}`);
  }

  const texts = new Texts();
  const entries = CONFIG.extraEntries(texts);
  for (const pkg of packages) {
    if (FIRST_PARTY.test(pkg.name)) {
      continue;
    }
    entries.push(crateEntry(pkg, texts));
  }

  const sections = [
    CONFIG.header,
    rule("Heartwood Core"),
    `The notice of Heartwood Core at the revision this build uses (heartwood-crypto ${heartwood.version},\n${sourceOf(heartwood)}):`,
    indent(readFileSync(heartwoodNotice, "utf8").trimEnd()),
    rule(`Third-party Rust code (${entries.length})`),
    "Each crate is listed with its version, its licence as its authors state it and, where they offer\n" +
      "a choice, the licence it is used under here, its source, and the copyright lines of its\n" +
      "licence files (or, where they have none, its authors). The licence texts are at the end.",
    entries.join("\n\n"),
    ...CONFIG.extraSections(texts),
    rule("Licence texts"),
    texts.render(),
  ];
  return `${sections.join("\n\n")}\n`;
}

function crateEntry(pkg, texts) {
  const stated = pkg.license ?? (pkg.license_file ? `see ${pkg.license_file}` : undefined);
  if (stated === undefined) {
    fail(`${pkg.name} ${pkg.version} states no licence`);
  }
  const chosen = pkg.license ? choose(pkg.license, pkg.name) : ["(the licence file)"];
  const lines = [`${pkg.name} ${pkg.version}`];
  const choice = pkg.license && chosen.join(" AND ") !== pkg.license.replaceAll("/", " OR ");
  lines.push(`  Licence: ${stated}${choice ? ` (used under ${chosen.join(" AND ")})` : ""}`);
  lines.push(`  Source: ${sourceOf(pkg)}`);

  const dir = dirname(pkg.manifest_path);
  const files = licenceFiles(dir);
  const copyrights = uniqueStatements(files.flatMap((file) => copyrightLines(readFileSync(join(dir, file), "utf8"))));
  for (const line of copyrights) lines.push(`  ${line}`);
  // Where no line names a holder, the manifest's authors do.
  if (!copyrights.some(namesHolder)) {
    lines.push(
      pkg.authors.length > 0
        ? `  Authors: ${pkg.authors.map(stripEmail).join(", ")}`
        : `  Authors: the ${pkg.name} developers (no copyright line in the package)`,
    );
  }

  addTexts(texts, chosen, dir, files, `${pkg.name} ${pkg.version}`);
  if (pkg.license_file) {
    texts.add("Licence file", readFileSync(join(dir, pkg.license_file), "utf8"), `${pkg.name} ${pkg.version}`);
  }

  // Apache-2.0, section 4(d): a NOTICE file of the work is passed on.
  for (const file of files.filter((f) => /^notice/i.test(f))) {
    lines.push(`  Its ${file} reads:`);
    lines.push(indent(readFileSync(join(dir, file), "utf8").trimEnd(), "    "));
  }

  for (const bundled of BUNDLED[pkg.name] ?? []) {
    const path = join(dir, bundled.file);
    if (!existsSync(path)) {
      fail(`${pkg.name} ${pkg.version}: ${bundled.file} is missing`);
    }
    const body = readFileSync(path, "utf8");
    lines.push(`  Bundles ${bundled.component}, under ${bundled.licence}:`);
    for (const line of copyrightLines(body)) lines.push(`    ${line}`);
    texts.add(bundled.licence, body, `${pkg.name} ${pkg.version} (${bundled.component})`);
  }
  return lines.join("\n");
}

// The texts of the licences a package is used under, other than Apache-2.0 (which is in LICENSE).
function addTexts(texts, chosen, dir, files, user) {
  for (const licence of chosen) {
    if (licence === "Apache-2.0" || licence === "(the licence file)") {
      continue;
    }
    const file = files.find((f) => detect(readFileSync(join(dir, f), "utf8")).has(licence));
    const body = file === undefined ? STANDARD[licence] : readFileSync(join(dir, file), "utf8");
    if (body === undefined) {
      fail(`${user}: no text of ${licence} in the package and none built in`);
    }
    texts.add(licence, body, user);
  }
}

function sourceOf(pkg) {
  const repository = pkg.repository?.replace(/\.git$/, "");
  if (pkg.source?.startsWith("registry+")) {
    return `https://crates.io/crates/${pkg.name}/${pkg.version}${repository ? `, ${repository}` : ""}`;
  }
  if (pkg.source?.startsWith("git+")) {
    const url = pkg.source.slice(4).replace(/^ssh:\/\/git@[^/]+\//, "https://github.com/");
    return url.replace(/\?.*#/, " at ").replace(/\.git /, " ");
  }
  return repository ?? "no repository stated";
}

// Licences -----------------------------------------------------------------------------------

// The licences a crate is used under: every licence of an AND, the preferred side of an OR.
function choose(expression, name) {
  const tokens = expression
    .replaceAll("/", " OR ")
    .replaceAll("(", " ( ")
    .replaceAll(")", " ) ")
    .split(/\s+/)
    .filter(Boolean);
  let at = 0;
  const rank = (set) => set.reduce((sum, id) => sum + rankOf(id), 0);
  const rankOf = (id) => {
    const index = PREFERENCE.indexOf(id);
    return index < 0 ? 1000 : index;
  };
  const expr = () => {
    let best = term();
    while (tokens[at] === "OR") {
      at++;
      const next = term();
      if (rank(next) < rank(best)) best = next;
    }
    return best;
  };
  const term = () => {
    let set = factor();
    while (tokens[at] === "AND") {
      at++;
      set = unique([...set, ...factor()]);
    }
    return set;
  };
  const factor = () => {
    const token = tokens[at++];
    if (token === "(") {
      const set = expr();
      if (tokens[at++] !== ")") fail(`${name}: unbalanced licence expression ${expression}`);
      return set;
    }
    if (token === undefined || ["AND", "OR", "WITH", ")"].includes(token)) {
      fail(`${name}: cannot read the licence expression ${expression}`);
    }
    if (tokens[at] === "WITH") {
      at++;
      return [`${token} WITH ${tokens[at++]}`];
    }
    return [token];
  };
  const chosen = expr();
  if (at !== tokens.length) fail(`${name}: cannot read the licence expression ${expression}`);
  for (const id of chosen) {
    if (!PREFERENCE.includes(id)) fail(`${name}: the licence ${id} is not one this project accepts`);
  }
  return chosen.sort((a, b) => rankOf(a) - rankOf(b));
}

// The licences whose text a file contains.
function detect(text) {
  const t = text.toLowerCase().replace(/\s+/g, " ");
  const found = new Set();
  if (t.includes("apache license") && t.includes("version 2.0")) found.add("Apache-2.0");
  if (t.includes("permission is hereby granted, free of charge")) {
    found.add(t.includes("unicode") && t.includes("data files") ? "Unicode-3.0" : "MIT");
  }
  if (t.includes("unicode license v3")) found.add("Unicode-3.0");
  if (/permission to use, copy, modify, and(\/or)? distribute this software for any purpose/.test(t)) found.add("ISC");
  if (t.includes("redistribution and use in source and binary forms")) {
    found.add(/neither the name|names of (its|the) contributors|may not be used to endorse/.test(t) ? "BSD-3-Clause" : "BSD-2-Clause");
  }
  if (t.includes("altered source versions must be plainly marked")) found.add("Zlib");
  if (t.includes("cc0 1.0 universal")) found.add("CC0-1.0");
  if (t.includes("free and unencumbered software released into the public domain")) found.add("Unlicense");
  if (/community data license agreement . permissive . version 2\.0/.test(t)) found.add("CDLA-Permissive-2.0");
  return found;
}

function licenceFiles(dir) {
  return readdirSync(dir)
    .filter((name) => /^(licen[cs]e|copying|copyright|notice|unlicense)/i.test(name))
    .filter((name) => statSync(join(dir, name)).isFile())
    .sort();
}

// The copyright statements of a licence file, without the licence's own wording about copyright.
function copyrightLines(text) {
  const lines = text.split(/\r?\n/).map((line) => line.replace(/^\s*(\/\/+|#+|\*+|--)\s?/, "").trim());
  const found = [];
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    const statement = /^(copyright\b|\(c\)\s*\d)/i.test(line) || /©/.test(line);
    if (!statement || BOILERPLATE.some((pattern) => pattern.test(line))) {
      continue;
    }
    // A statement that ends after its years continues on the next line.
    if (!namesHolder(line) && lines[i + 1]) {
      line = `${line} ${lines[i + 1]}`;
      i++;
    }
    // Contact addresses are not part of a statement; the entry names the holder only.
    found.push(stripEmail(line).replace(/\s+/g, " "));
  }
  return found;
}

const BOILERPLATE = [
  /[[{<](yyyy|year)[\]}>]|name of copyright owner|<copyright holders?>/i,
  /^copyright assignment/i,
  /^copyright license/i,
  /^copyright and related rights/i,
  /^copyright (notice|holder|owner|statement)/i,
  /^copyright,? patent/i,
  /^copyright and permission notice$/i,
  /^copyright (law|laws)\b/i,
];

// Built-in texts for licences whose crates ship no licence file.
const STANDARD = {
  MIT: `Permission is hereby granted, free of charge, to any person obtaining a copy of this software
and associated documentation files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute,
sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
`,
  ISC: `Permission to use, copy, modify, and/or distribute this software for any purpose with or without
fee is hereby granted, provided that the above copyright notice and this permission notice appear
in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS
SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
`,
};

// Each distinct licence text once, with the crates that use it. Texts that differ only in their
// copyright lines (which each crate's entry lists) count as one.
class Texts {
  constructor() {
    this.byKey = new Map();
  }

  add(licence, body, user) {
    // Without the copyright lines, which each crate's entry lists, and without a title line.
    const kept = body
      .split(/\r?\n/)
      .filter((line) => copyrightLines(line).length === 0)
      .join("\n")
      .replace(/^\s*(the )?mit license( \(mit\))?\s*\n/i, "")
      .replace(/\n\s*\n(\s*\n)+/g, "\n\n")
      .replace(/^\s*\n/, "")
      .trimEnd();
    const key = kept.toLowerCase().replace(/[\s*#/-]+/g, " ").trim();
    const entry = this.byKey.get(key) ?? { licences: [], text: kept, users: [] };
    if (!entry.licences.includes(licence)) entry.licences.push(licence);
    if (!entry.users.includes(user)) entry.users.push(user);
    this.byKey.set(key, entry);
  }

  render() {
    const parts = [
      "Apache-2.0: the Apache License, Version 2.0, whose text is in LICENSE, covers every crate used\nunder Apache-2.0 above.",
    ];
    const order = (entry) => Math.min(...entry.licences.map((id) => PREFERENCE.indexOf(id)));
    const entries = [...this.byKey.values()].sort(
      (a, b) => order(a) - order(b) || compareText(a.users[0], b.users[0]),
    );
    for (const { licences, text, users } of entries) {
      const names = licences.sort((a, b) => PREFERENCE.indexOf(a) - PREFERENCE.indexOf(b)).join(", ");
      parts.push(`----- ${names}: the text for ${users.join(", ")}\n\n${indent(text)}`);
    }
    return parts.join("\n\n");
  }
}

// Helpers ------------------------------------------------------------------------------------

function rule(title) {
  return `${"=".repeat(100)}\n${title}\n${"=".repeat(100)}`;
}

function indent(text, prefix = "  ") {
  return text
    .split("\n")
    .map((line) => (line.trim() === "" ? "" : `${prefix}${line.replace(/\s+$/, "")}`))
    .join("\n");
}

function namesHolder(line) {
  return /[a-z]{3,}/i.test(line.replace(/copyright|\(c\)|all rights reserved/gi, ""));
}

// The same statement once, however its files write the copyright sign.
function uniqueStatements(lines) {
  const seen = new Set();
  return lines.filter((line) => {
    const key = line.toLowerCase().replace(/\(c\)|©|[,.]/g, "").replace(/\s+/g, " ").trim();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function stripEmail(text) {
  return text
    .replace(/\s*[<(][^<>()\s]+@[^<>()\s]+[>)]/g, "")
    .replace(/\s*<[^>]*>/g, "")
    .replace(/\s*\S+@\S+\.[a-z]{2,}/gi, "")
    .trim();
}

// Words of `text` in lines of at most 100 characters, each after `prefix`.
function wrap(text, prefix) {
  const lines = [];
  let line = prefix;
  for (const word of text.split(" ")) {
    if (line.length > prefix.length && line.length + 1 + word.length > 100) {
      lines.push(line);
      line = `${prefix}  ${word}`;
    } else {
      line = line.length > prefix.length ? `${line} ${word}` : `${line}${word}`;
    }
  }
  lines.push(line);
  return lines.join("\n");
}

function unique(list) {
  return [...new Set(list)];
}

function fail(message) {
  console.error(`notice: ${message}`);
  process.exit(1);
}

main();
